In [2]:
import pandas as pd
import numpy as np
import pickle
import os
from scipy.fftpack import fft, fftfreq
import matplotlib as mpl
import matplotlib.pyplot as plt


%load_ext autoreload
%autoreload 2

from formata_dados import *
from processa_dados import *

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [3]:
#pasta na qual estão os arquivos de dados
path = "Dataset\\EXPERIMENTO OFICIAL 2019/"

In [4]:
#dicionário
## chave: nome do arquivo, valor: dados
#### Cada voluntário participou do experimento 3 dias, ingerindo 2 vezes cada uma das 4 bebidas
######(agua, suco com aspartame, suco com acucar. suco com sucralose) em cada dia.
##### 11 voluntários = 264 dados
##### 64 dados descartados -> 200 dados válidos
dados_voluntarios_completos = le_dados_EEG(path)

In [5]:
dados_voluntarios_completos['beatriz3872'][0]

            Time           1           2
0       0.000000   51.430533  100.137331
1       0.001953   25.612268   67.360952
2       0.003906    4.234379   36.781872
3       0.005859   -9.498741   13.435569
4       0.007813  -14.351110    0.114443
...          ...         ...         ...
10235  19.990234   95.925841  102.838178
10236  19.992188  138.132296  151.499199
10237  19.994141  170.908675  191.325246
10238  19.996094  187.937743  214.717327
10239  19.998047  185.740444  216.823072

[10240 rows x 3 columns]

In [6]:
lista_dados = list(dados_voluntarios_completos.values())
nome_dos_arquivos = list(dados_voluntarios_completos.keys())
output = cria_dicionario_output()

In [7]:
#referencias das bebidas
agua = 0
acucar = 1
aspartame = 2
sucralose = 3
dict_output = enumera_dicionario(['agua', 'acucar', 'aspartame', 'sucralose'])

In [8]:
#referencia das datas
dicionario_datas = inverte_enumera_dicionario(['07.11','08.11','11.11','12.11','13.11','14.11','27.11','28.11','02.12','03.12','04.12'])
inverte_enumera_dicionario = enumera_dicionario(['07.11','08.11','11.11','12.11','13.11','14.11','27.11','28.11','02.12','03.12','04.12'])

In [9]:
#referencia dos individuos
dict_individuo = enumera_dicionario(['Camila Mendes', 'Camila Gomes','Beatriz','Carol Monica', 
                                    'Isabella','Isa Peron','Lais','Maria Clara','Orlando','Rafaela'])
camilamendes = 0
camila = 1 #camila gomes
beatriz = 2
carolmonica = 3
isabella = 4
isaperon = 5
lais = 6
mariaclara = 7
orlando = 8
rafa = 9

In [10]:
#Enumera as bebidas ingeridas e nomeia os voluntatios participantes de cada experimento
lista_output, individuos = arruma_output(nome_dos_arquivos, output, acucar, agua, sucralose, aspartame)

In [11]:
len(lista_output), len(individuos)

(200, 200)

In [12]:
#Deixa todos os vetores com o mesmo tamanho
lista_dados_padronizados, data_experimento = padroniza_dados(lista_dados)

Os dados foram padronizados

In [13]:
#enumera os voluntarios participantes de cada experimento
lista_individuos = gera_lista_individuos(individuos, camilamendes, camila, beatriz, carolmonica, isabella, isaperon, lais, mariaclara, orlando, rafa)

In [14]:
len(lista_individuos)

200

In [15]:
#Se False: Carrega dados
#Se True: Gera dados
carregar_dados = True

if carregar_dados:
    dados_originais = completa_dados(lista_dados_padronizados,lista_output, dicionario_datas, lista_individuos, data_experimento)
    with open("Dataset\\dados_pickle\\dados_originais.pkl", "wb") as originais:
        pickle.dump([dados_originais], originais)
else:
    with open("Dataset\\dados_pickle\\dados_originais.pkl", "rb") as originais:
        dados_originais = pickle.load(originais)
        dados_originais = dados_originais[0]

In [16]:
dados_originais

,0,1,2,3,4,5,6,7,8,9,...,9210,9211,9212,9213,9214,9215,9216,9217,9218,9219
0,51.430533,25.612268,4.234379,-9.498741,-14.351110,-11.421378,-3.410391,6.202792,14.488441,19.386587,...,5.928130,6.019684,5.241474,3.639277,1.487755,-0.938430,1.0,1.0,1.0,2.0
1,100.137331,67.360952,36.781872,13.435569,0.114443,-3.227283,1.167315,9.727626,18.654154,25.200275,...,-4.234379,-0.389105,2.723735,4.737926,5.516136,5.104143,2.0,1.0,1.0,2.0
2,5.745022,-22.362097,-42.961776,-53.124285,-52.574960,-43.373770,-29.091325,-13.710231,-0.663767,8.125429,...,2.357519,1.945525,2.311742,3.547723,5.424582,7.530327,1.0,2.0,1.0,2.0
3,45.433738,10.826276,-17.830167,-36.415656,-43.419547,-40.123598,-30.052644,-17.372396,-5.973907,1.625086,...,9.681849,13.252461,15.861753,17.189288,17.097734,15.495537,2.0,2.0,1.0,2.0
4,-150.080110,-112.726024,-67.498283,-22.224765,16.090639,42.687114,55.962463,57.244221,50.057221,38.933394,...,-4.966812,-5.287251,-6.248569,-7.804990,-9.773404,-11.833371,1.0,3.0,1.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,-324.765393,-256.466011,-166.559854,-70.565347,15.815976,80.315862,116.342412,123.620966,107.232776,75.738155,...,-11.604486,-8.812085,-6.843671,-5.653468,-4.875257,-4.325933,2.0,2.0,5.0,9.0
396,4.554818,-29.869535,-47.539483,-44.426642,-21.904326,13.756008,52.666514,84.023804,99.038682,93.362325,...,-31.197070,-75.783932,-115.381094,-138.406958,-132.547494,-88.006409,1.0,0.0,5.0,9.0
397,-89.425498,-125.909819,-141.748684,-135.568780,-110.986496,-75.646601,-39.070726,-10.322728,4.280156,2.540627,...,-9.132525,-28.999771,-47.814145,-61.318379,-65.026322,-55.230030,2.0,0.0,5.0,9.0
398,227.214466,195.124743,156.534676,121.560998,98.992905,94.552529,109.933623,142.984665,188.899062,241.542687,...,-105.264363,-103.753719,-97.940032,-87.502861,-71.663996,-49.462119,1.0,0.0,5.0,9.0
399,291.302358,232.387274,161.478599,92.858778,39.070726,8.583200,4.234379,23.414969,59.533074,104.165713,...,-63.424125,-54.406043,-42.275120,-28.130007,-12.840467,2.723735,2.0,0.0,5.0,9.0

In [17]:
# ordena os dados originais por data e por individuo - coluna 9218 = data, coluna 9219 = individuo
dados_originais_ordenados = dados_originais.sort_values([9218,9219])

In [18]:
dados_originais_ordenados

,0,1,2,3,4,5,6,7,8,9,...,9210,9211,9212,9213,9214,9215,9216,9217,9218,9219
112,-293.270771,-262.829023,-209.498741,-143.625544,-76.928359,-19.707027,21.309224,43.923095,50.286107,45.433738,...,54.634928,42.915999,15.678645,-23.186084,-66.628519,-105.767910,1.0,2.0,0.0,3.0
113,-276.836805,-252.758068,-203.959716,-140.146487,-73.174640,-14.122225,29.182879,53.353170,59.670405,52.803845,...,93.316548,91.714351,70.153353,31.563287,-16.914626,-65.575647,2.0,2.0,0.0,3.0
114,-220.302129,-146.784161,-66.216526,7.713436,63.973449,96.200504,103.707942,90.661479,64.293889,32.982376,...,98.443580,120.553902,123.346304,105.539025,70.473793,25.429160,1.0,1.0,0.0,3.0
115,-269.192035,-195.994507,-113.458457,-35.912108,25.017166,62.600137,75.921263,69.192035,49.919890,26.390478,...,81.139849,114.282444,129.068437,121.972992,94.323644,52.254520,2.0,1.0,0.0,3.0
116,-77.889677,-104.257267,-114.373999,-108.239872,-89.425498,-63.836118,-37.651637,-16.044862,-1.625086,5.516136,...,146.646830,204.829480,245.983062,261.913481,249.095903,209.956512,1.0,2.0,0.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
299,-70.336461,-78.255894,-81.826505,-81.368734,-78.072786,-73.220417,-68.276493,-64.156558,-61.501488,-60.311284,...,7.988098,-2.494850,-12.748913,-21.171893,-26.344701,-27.580682,2.0,1.0,10.0,7.0
300,103.341726,128.061341,149.301900,165.323873,175.211719,178.965438,177.500572,172.281987,165.049210,157.495995,...,30.876631,30.052644,27.992676,25.108721,21.812772,18.287938,1.0,0.0,10.0,7.0
301,115.609979,126.733806,134.790570,140.100710,143.030442,144.129091,143.762875,142.435340,140.558480,138.498512,...,9.178302,5.516136,-1.075761,-9.224079,-17.097734,-23.002976,2.0,0.0,10.0,7.0
302,1.304646,10.643168,20.576791,29.961089,37.651637,43.053330,45.983062,46.623941,45.616846,43.602655,...,142.893111,138.040742,128.747997,114.831769,96.795605,75.875486,1.0,0.0,10.0,7.0
303,11.146715,9.910735,10.505837,13.160906,17.692836,23.414969,29.503319,35.088121,39.665827,42.824445,...,116.571298,103.204395,88.509957,73.586633,59.304189,46.211948,2.0,0.0,10.0,7.0

In [19]:
# transforma os dados originais de pandas.DataFrame para numpy.array
dados_numpy = np.array(dados_originais_ordenados)

In [20]:
ok, errado = valida_dados(dados_numpy[:,:-4])

In [21]:
len(ok), len(errado)

(68, 332)

In [22]:
#como a funcao "valida_dados" retorna os indices dos vetores, aqui os vetores corretos estao sendo filtrados 
dados_numpy_ok = dados_numpy[ok]

In [23]:
dados_numpy_ok.shape

(68, 9220)

In [24]:
#separa os dados por bebida
dados_separados_por_output = separa_dados_por_output(dados_numpy_ok,dict_output)

In [25]:
dados_separados_por_output['agua'].shape, dados_separados_por_output['aspartame'].shape, dados_separados_por_output['sucralose'].shape, dados_separados_por_output['acucar'].shape

((16, 9220), (19, 9220), (17, 9220), (16, 9220))

In [32]:
save_to_pickle = False
if save_to_pickle:
    with open("Dataset/dados_pickle/dados_ok.pkl", "wb") as dados_ok:
            pickle.dump([dados_numpy_ok], dados_ok)
    with open("Dataset/dados_pickle/dados_agua_ok.pkl", "wb") as dados_agua_ok:
            pickle.dump([dados_separados_por_output['agua']], dados_agua_ok)
    with open("Dataset/dados_pickle/dados_aspartame_ok.pkl", "wb") as dados_aspartame_ok:
            pickle.dump([dados_separados_por_output['aspartame']], dados_aspartame_ok)
    with open("Dataset/dados_pickle/dados_sucralose_ok.pkl", "wb") as dados_sucralose_ok:
            pickle.dump([dados_separados_por_output['sucralose']], dados_sucralose_ok)
    with open("Dataset/dados_pickle/dados_acucar_ok.pkl", "wb") as dados_acucar_ok:
            pickle.dump([dados_separados_por_output['acucar']], dados_acucar_ok)
    with open("Dataset/dados_pickle/todos_os_dados_originais.pkl", "wb") as todos_os_dados:
            pickle.dump([dados_numpy], todos_os_dados)

In [27]:
#nomeia as colunas de output
tabela_dados = pd.DataFrame(dados_numpy_ok)
tabela_dados.rename(columns={9216:'Canal'}, inplace = True)
tabela_dados.rename(columns={9217:'Bebida'}, inplace = True)
tabela_dados.rename(columns={9218:'Data'}, inplace = True)
tabela_dados.rename(columns={9219:'Individuo'}, inplace = True)

In [28]:
tabela_dados

,0,1,2,3,4,5,6,7,8,9,...,9210,9211,9212,9213,9214,9215,Canal,Bebida,Data,Individuo
0,-293.270771,-262.829023,-209.498741,-143.625544,-76.928359,-19.707027,21.309224,43.923095,50.286107,45.433738,...,54.634928,42.915999,15.678645,-23.186084,-66.628519,-105.767910,1.0,2.0,0.0,3.0
1,-276.836805,-252.758068,-203.959716,-140.146487,-73.174640,-14.122225,29.182879,53.353170,59.670405,52.803845,...,93.316548,91.714351,70.153353,31.563287,-16.914626,-65.575647,2.0,2.0,0.0,3.0
2,-220.302129,-146.784161,-66.216526,7.713436,63.973449,96.200504,103.707942,90.661479,64.293889,32.982376,...,98.443580,120.553902,123.346304,105.539025,70.473793,25.429160,1.0,1.0,0.0,3.0
3,-269.192035,-195.994507,-113.458457,-35.912108,25.017166,62.600137,75.921263,69.192035,49.919890,26.390478,...,81.139849,114.282444,129.068437,121.972992,94.323644,52.254520,2.0,1.0,0.0,3.0
4,-77.889677,-104.257267,-114.373999,-108.239872,-89.425498,-63.836118,-37.651637,-16.044862,-1.625086,5.516136,...,146.646830,204.829480,245.983062,261.913481,249.095903,209.956512,1.0,2.0,0.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63,198.374914,193.934539,166.285191,121.652552,69.283589,19.295033,-20.164797,-44.151980,-52.025635,-46.578164,...,-21.675441,-24.925612,-25.474937,-23.140307,-18.013275,-10.414282,2.0,0.0,5.0,1.0
64,-174.433509,-154.657816,-110.849165,-51.384756,12.153811,67.589837,105.264363,119.958801,111.718929,85.397116,...,20.347906,17.555505,11.512932,2.494850,-8.583200,-20.256352,2.0,3.0,5.0,9.0
65,326.413367,254.039826,164.637217,73.311971,-5.790799,-62.371252,-91.622797,-94.232090,-75.326162,-42.641337,...,-110.482948,-71.892882,-9.407187,67.452506,144.403754,205.882353,2.0,1.0,5.0,9.0
66,-337.903410,-272.945754,-187.251087,-95.056077,-10.322728,56.237125,98.901350,117.303731,115.518425,100.045777,...,-40.947585,-33.257038,-21.721218,-7.759213,6.889448,20.393683,1.0,2.0,5.0,9.0
67,-324.765393,-256.466011,-166.559854,-70.565347,15.815976,80.315862,116.342412,123.620966,107.232776,75.738155,...,-11.604486,-8.812085,-6.843671,-5.653468,-4.875257,-4.325933,2.0,2.0,5.0,9.0

In [29]:
#nomeia os outputs
for i in list(range(4)):
    tabela_dados['Bebida'] = tabela_dados['Bebida'].replace(i, dict_output[i])
for i in range(len(inverte_enumera_dicionario)):
    tabela_dados['Data'] = tabela_dados['Data'].replace(i, inverte_enumera_dicionario[i])
for i in range(len(dict_individuo)):
    tabela_dados['Individuo'] = tabela_dados['Individuo'].replace(i, dict_individuo[i])

In [30]:
tabela_dados

,0,1,2,3,4,5,6,7,8,9,...,9210,9211,9212,9213,9214,9215,Canal,Bebida,Data,Individuo
0,-293.270771,-262.829023,-209.498741,-143.625544,-76.928359,-19.707027,21.309224,43.923095,50.286107,45.433738,...,54.634928,42.915999,15.678645,-23.186084,-66.628519,-105.767910,1.0,aspartame,07.11,Carol Monica
1,-276.836805,-252.758068,-203.959716,-140.146487,-73.174640,-14.122225,29.182879,53.353170,59.670405,52.803845,...,93.316548,91.714351,70.153353,31.563287,-16.914626,-65.575647,2.0,aspartame,07.11,Carol Monica
2,-220.302129,-146.784161,-66.216526,7.713436,63.973449,96.200504,103.707942,90.661479,64.293889,32.982376,...,98.443580,120.553902,123.346304,105.539025,70.473793,25.429160,1.0,acucar,07.11,Carol Monica
3,-269.192035,-195.994507,-113.458457,-35.912108,25.017166,62.600137,75.921263,69.192035,49.919890,26.390478,...,81.139849,114.282444,129.068437,121.972992,94.323644,52.254520,2.0,acucar,07.11,Carol Monica
4,-77.889677,-104.257267,-114.373999,-108.239872,-89.425498,-63.836118,-37.651637,-16.044862,-1.625086,5.516136,...,146.646830,204.829480,245.983062,261.913481,249.095903,209.956512,1.0,aspartame,07.11,Carol Monica
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63,198.374914,193.934539,166.285191,121.652552,69.283589,19.295033,-20.164797,-44.151980,-52.025635,-46.578164,...,-21.675441,-24.925612,-25.474937,-23.140307,-18.013275,-10.414282,2.0,agua,14.11,Camila Gomes
64,-174.433509,-154.657816,-110.849165,-51.384756,12.153811,67.589837,105.264363,119.958801,111.718929,85.397116,...,20.347906,17.555505,11.512932,2.494850,-8.583200,-20.256352,2.0,sucralose,14.11,Rafaela
65,326.413367,254.039826,164.637217,73.311971,-5.790799,-62.371252,-91.622797,-94.232090,-75.326162,-42.641337,...,-110.482948,-71.892882,-9.407187,67.452506,144.403754,205.882353,2.0,acucar,14.11,Rafaela
66,-337.903410,-272.945754,-187.251087,-95.056077,-10.322728,56.237125,98.901350,117.303731,115.518425,100.045777,...,-40.947585,-33.257038,-21.721218,-7.759213,6.889448,20.393683,1.0,aspartame,14.11,Rafaela
67,-324.765393,-256.466011,-166.559854,-70.565347,15.815976,80.315862,116.342412,123.620966,107.232776,75.738155,...,-11.604486,-8.812085,-6.843671,-5.653468,-4.875257,-4.325933,2.0,aspartame,14.11,Rafaela